controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Question;
use app\models\Answer;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use kartik\mpdf\Pdf;
use yii\helpers\FileHelper;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }


    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $question = new Question();
        $answer = new Answer();
        return $this->render('index', ['question' => $question, 'answer' => $answer]);
    }

    public function actionArr()
    {
        $percentArr = [];
        $allAnswers = ArrayHelper::map(Answer::find()->where(['question_id' => 1])->all(), 'id', 'given');
        $sum = array_sum($allAnswers);
        foreach ($allAnswers as $key => $val) {
            $percentArr[] = [$key => [100 - ($sum - $val) * 100 / $sum]];
        }
    }

    public function actionBeginTest()
    {
        $name = Yii::$app->request->post('name');
        $email = Yii::$app->request->post('email');
        Yii::$app->session->set('name',$name);
        Yii::$app->session->set('email',$email);
        $question = Question::find()->where(['number' => 1])->one();
        $image = "/images/question/{$question->id}/image_initial.jpg";
        return json_encode(['image'=>$image]);

    }

    public function actionCheckAnswer()
    {
        $answer_id = (int)Yii::$app->request->post('answer');
        $question_id = Yii::$app->request->post('question');
        $question = Question::find()->where(['id' => $question_id])->one();

        $exp = Answer::findOne($answer_id);
        $newGiven = $exp->given = $exp->given + 1;
        Yii::$app->db->createCommand("UPDATE answer SET given=:column1 WHERE id=:id")
            ->bindValue(':id', $answer_id)
            ->bindValue(':column1', $newGiven)->execute();


        $percentArr = [];
        $allAnswers = ArrayHelper::map(Answer::find()->where(['question_id' => $question_id])->orderBy(['priority' => SORT_ASC])->all(), 'id', 'given');
        $sum = array_sum($allAnswers);
        if ($sum == 0) {
            $sum = 1;
        }
        foreach ($allAnswers as $key => $val) {
            $percentArr[] = 100 - ($sum - $val) * 100 / $sum;
        }

        $image = "/images/question/{$question->id}/image_after.jpg";
        //$image = "/images/primary.jpg";

        if ($question->correct_option_id == $answer_id) {
            return json_encode(['correct' => 'true','explanation' => $question->right_explanation, 'image' => $image, 'percent' => $percentArr]);
        } else {
            return json_encode(['correct' => 'false','explanation' => $question->explanation, 'image' => $image, 'percent' => $percentArr, 'correct' => "option-{$question->correct_option_id}"]);
        }

    }

    public function actionNextQuestion()
    {
        $number = Yii::$app->request->post('number') + 1;
        $question = Question::find()->where(['number' => $number])->one();
        if ($question) {
            //$image = "/images/question/{$question->id}/image_initial.jpg";
            $image = "/images/question/{$question->id}/image_initial.jpg";
            $ansArr = [];
            $answers = Answer::find()->where(['question_id' => $question->id])->all();
            foreach ($answers as $ans) {
                $ansArr[] = ['id' => $ans->id, 'title' => $ans->title, 'description' => $ans->description];
            }
            $arr = ['question' => $question->title, 'mid' => $question->id, 'answer' => $ansArr, 'image' => $image];
            return json_encode($arr);
        } else {
            $this->redirect(Yii::$app->urlManager->createUrl('site/finish'));
        }
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function sendCert($email)
    {
        Yii::$app->mailer->compose('layouts/html', ['subject' => "Сертификат"])
            ->setBcc($email)
            ->setFrom(['genderquiz@prosoft.kg' => 'Квиз по тексту'])
            ->setSubject("Сертификат")
            ->setTextBody("")
            ->send();
    }

    public function actionSendEmail(){
        $email = "damirbek@gmail.com";
        Yii::$app->mailer->compose()
            ->setTo('damirbek@gmail.com')
            ->setFrom([Yii::$app->params['adminEmail'] => 'Quiz.kg'])
            ->setSubject('Call me maybe')
            ->setTextBody("Client name: ")
            ->setHtmlBody("<strong>Client name</strong>test<br /><strong>Client phone</strong>:test<br /><strong>test</strong>")
            ->send();
    }


    public function actionFinish()
    {
        $imageUrl = Url::base() . '/images/cert_bg.jpg';
        $name =  Yii::$app->session['name'];
        $email = Yii::$app->session['email'];
        Yii::$app->response->format = \yii\web\Response::FORMAT_RAW;
        $dir = Yii::getAlias("@webroot/files/{$email}");
        $string = str_replace("_", " ", $name);
        FileHelper::createDirectory($dir);
        $pdf = new Pdf([
            'mode' => Pdf::MODE_UTF8,
            'destination' => Pdf::DEST_FILE,
            'cssFile' => 'css/cert.css',
            'filename'=>"{$dir}/certificate.pdf",
            //'cssFile' => '@web/css/cert.css',
            // any css to be embedded if required
            'cssInline' => ".certificate_bg{background-image: url({$imageUrl});background-repeat: no-repeat;background-size: cover;height:100%;width:100%}",
            'orientation' => Pdf::ORIENT_LANDSCAPE,
            'marginLeft' => 0,
            'marginTop' => 0,
            'marginRight' => 0,
            'marginBottom' => 0,
            'content' => $this->renderPartial('privacy',['name'=>$name]),
            'options' => [
                // any mpdf options you wish to set
            ],
            'methods' => [
                /*'SetTitle' => 'Privacy Policy - Krajee.com',
                'SetSubject' => 'Generating PDF files via yii2-mpdf extension has never been easy',
                'SetHeader' => ['Krajee Privacy Policy||Generated On: ' . date("r")],
                'SetFooter' => ['|Page {PAGENO}|'],
                'SetAuthor' => 'Kartik Visweswaran',
                'SetCreator' => 'Kartik Visweswaran',
                'SetKeywords' => 'Krajee, Yii2, Export, PDF, MPDF, Output, Privacy, Policy, yii2-mpdf',*/
            ]
        ]);

        $pdf->render();
        Yii::$app->mailer->compose()
            ->setTo($email)
            ->setFrom([Yii::$app->params['adminEmail'] => 'Quiz.kg'])
            ->setSubject('Сертификат')
            ->setTextBody("Уважаемый {$name}")
            ->setHtmlBody("<strong>{$name}</strong>")
            ->attach("{$dir}/certificate.pdf")
            ->send();
        $this->render('finish');
    }

    public function actionReport()
    {
        // get your HTML raw content without any layouts or scripts
        $content = $this->renderPartial('_reportView');

        // setup kartik\mpdf\Pdf component
        $pdf = new Pdf([
            // set to use core fonts only
            'mode' => Pdf::MODE_CORE,
            // A4 paper format
            'format' => Pdf::FORMAT_A4,
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT,
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER,
            // your html content input
            'content' => $content,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting
            'cssFile' => '@web/css/cert.css',
            // any css to be embedded if required
            'cssInline' => '.kv-heading-1{font-size:18px}',
            // set mPDF properties on the fly

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use app\models\Question;
use app\models\Answer;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;

/* @var $this yii\web\View */

$this->title = 'Тест по гендерным курсам';
?>
<div class="container">
    <div class="site-index">
        <div class="general-container">

            <div class="question-form">
                <?php $form = ActiveForm::begin(['action' => ['site/generate-cert']]);
                $count_quest = Question::find()->count(); ?>
                <div class="title_heading" style="padding: 10px 20px 0px;">Тест на закрепление знаний на основе гендерных курсов</div>
                <div class="intro-form">
                    <div style="padding: 10px 20px;">
                        <div class="intro-text">
                            Вы собираетесь пройти тест на закрепление пройденного теста на гендерных курсах. Пожалуйста,
                            помогите нам сделать мир лучше, оставьте свои данные в норме ниже
                        </div>
                        <?= $form->field($question, 'name')->textInput(['maxlength' => true, 'placeholder' => $question->getAttributeLabel('name')])->label(false) ?>
                        <?= $form->field($question, 'email')->textInput(['maxlength' => true, 'placeholder' => $question->getAttributeLabel('email')])->label(false) ?>
                    </div>
                    <?= Html::img(Url::base() . '/images/primary.jpg', ['style' => 'width:100%']); ?>
                    <div class="form-group" style="margin-top: 20px;">
                        <?= Html::button('Начать тест', ['class' => 'test-begin btn-primary btn']) ?>
                    </div>
                </div>

                <?php ActiveForm::end(); ?>


                <div class="quest-count" data-count="<?= $count_quest ?>" data-right="0"></div>
                <?php

                $question = Question::find()->where(['number' => 1])->one(); ?>
                <div class="primary-form" data-number="<?= $question->number ?>" data-id="<?= $question->id ?>">
                    <?php
                    echo $question->getImage();
                    echo Html::tag('div', '', ['class' => 'clear']);
                    echo Html::tag('h2', $question->title, ['class' => 'question-name']);

                    $answers = Answer::find()->where(['question_id' => $question->id])->orderBy(['priority' => SORT_ASC])->all(); ?>
                    <div class="answer-block">
                        <?php
                        if ($answers) {
                            foreach ($answers as $answer) {
                                echo Html::beginTag('div', [
                                    'class' => "option-hover answer-option option-$answer->id",
                                    'data-id' => $answer->id,
                                    'data-question' => $question->id
                                ]);
                                echo Html::tag('div', "<div class=ans-title-wrap>".$answer->title."</div>",
                                    [
                                        'class' => 'long-div'
                                    ]);
                                echo Html::endTag('div');
                            }
                        }
                        ?>
                    </div>
                </div>
            </div>
            <div class="footer-form"></div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var num_quest = 1;
    var count_quest = parseInt($('.quest-count').attr('data-count'));

    $('.test-begin').on('click', function (e) {
            var name = $('#question-name').val();
            var email = $('#question-email').val();
            if (name != "" && email != "") {
                $.ajax({
                    method: "POST",
                    url: "<?=Yii::$app->urlManager->createUrl('/site/begin-test');?>",
                    data: {name: name, email: email},
                    success: function (response) {
                        var obj = JSON.parse(response);
                        $('.intro-form').fadeOut();
                        $('.primary-form').css('display', 'block');
                        $('.MediaBlock-image ').css('background-image', 'url(' + obj.image + ')');
                        $('.footer-form').text(num_quest + "/" + count_quest);

                        sessionStorage.setItem('name', name);
                        sessionStorage.setItem('email', email);
                    }
                });
            }
            else {
                $('.intro-form').append("<div class='attention'>Необходимо ввести ФИО и Email</div>")
                if (name != "") {
                    $('.field-question-name').addClass('has-error');
                }
                if (email != "") {
                    $('.field-question-email').addClass('has-error');
                }
            }
        }
    );


    $(document).on('click', '.answer-option', function () {
        if (!$(this).hasClass('checked')) {
            $('.answer-option').addClass('checked');
            $('.answer-block').addClass('checked-hover');
            var answer_id = $(this).attr('data-id');
            var thisOne = $(this);
            var question_id = $(this).attr('data-question');
            $.ajax({
                method: "POST",
                url: "<?=Yii::$app->urlManager->createUrl('/site/check-answer');?>",
                data: {answer: answer_id, question: question_id},
                success: function (response) {
                    $(".answer-option").removeClass('option-hover');
                    var obj = JSON.parse(response);
                    var fill_string =  "";
                    $(".answer-option").each(function (index) {
                        console.log(obj.percent[index]);
                        fill_string =  "to right, #87dd47 0%,#87dd47 " + obj.percent[index] + "%,#a8f371 " + obj.percent[index] + "%,#a8f371 " + (100 - parseFloat(obj.percent[index])) +"%,#a8f371 100%";
                        if(obj.correct == false){
                            fill_string = "to right, #EA7C7C 0%,#EA7C7C " + obj.percent[index] + "%,#EDAAAA " + obj.percent[index] + "%,#EDAAAA " + (100 - parseFloat(obj.percent[index])) +"%,#EDAAAA 100%";
                        }
                        //fill_string =  "to right, #b7b7b7 0%,#b7b7b7 " + obj.percent[index] + "%,#e5e5e5 " + obj.percent[index] + "%,#e5e5e5 " + (100 - parseFloat(obj.percent[index])) +"%,#e5e5e5 100%";
                        $(this).css('background', 'linear-gradient('+fill_string+')');
                        $(this).find('.long-div').append("<span class='ans-percentage'>" + Math.round(obj.percent[index]) + "%</span>");
                    });
                    //console.log(obj);
                    if (obj.correct == 'true') {
                        thisOne.css('filter','none');
                        var right_ans = parseInt($('.quest-count').attr('data-right'));
                        $('.quest-count').attr('data-right', right_ans + 1);
                        $('.primary-form').append("<div class='next-q'><h2 class=ans-true>Верно</h2><div class=ans-explanation><div style=text-align:left> " + obj.explanation + "</div><br><div class=clear>Узнайте больше, посмотрев гендерные курсы.</div><div class='forward btn btn-primary'>Далее</div></div>");

                    }
                    else {

                        var myClass = obj.correct;
                        $("." + myClass).css('filter','none');
                        thisOne.css('filter','hue-rotate(-85deg)');
                        $('.primary-form').append("<div class='next-q'><h2 class=ans-wrong>Неверно</h2><div class=ans-explanation><div style=text-align:left> " + obj.explanation + "</div><br><div class=clear>Узнайте больше, посмотрев гендерные курсы.</div><div class='forward btn btn-primary'>Далее</div></div>");
                        $('.MediaBlock-image').html('<iframe width="770" height="360" src="https://www.youtube.com/embed/videoseries?list=PLLyBDdIWhtYG3UqGLL7mXjE_BePCntUyP" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>');

                    }
                }
            });

        }
    });


    $(document).on('click', '.forward', function () {
        var number = parseInt($('.primary-form').attr('data-number'));
        var count_quest = parseInt($('.quest-count').attr('data-count'));
        var right_count = parseInt($('.quest-count').attr('data-right'));
        $.ajax({
            method: "POST",
            url: "<?=Yii::$app->urlManager->createUrl('/site/next-question');?>",
            data: {number: number,right_count: right_count},
            success: function (response) {
                if (response != 'false') {
                    var obj = JSON.parse(response);
                    $('.MediaBlock-image ').css('background-image', 'url(' + obj.image + ')').html('');
                    $('.question-name').text(obj.question);
                    $('.answer-block').html('');
                    $.each(obj.answer, function (key, value) {
                        var classString = "option-hover answer-option option-" + value.id;
                        $('.answer-block').append("<div class='" + classString + "' data-id=" + value.id + " data-question=" + obj.mid + "><div class=long-div><div class=ans-title-wrap>" + value.title + "</div></div></div>");
                    });
                    $('.footer-form').text(number+1 + "/" + count_quest);
                    $('.primary-form').attr('data-number', number + 1);
                    $('.next-q').remove();
                }
                else {
                    var obj = sessionStorage.getItem('user');
                    console.log(obj);
                    $('.question-name').text("Ваш результат " + $('.quest-count').attr('data-right') + " из " + $('.quest-count').attr('data-count'));
                    $('.answer-block').remove();
                    $('.next-q').remove();
                }
            }
        });
    });
</script>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/privacy.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;


/* @var $this yii\web\View */

$this->title = 'Тест по гендерным курсам';
?>
<div class="certificate_bg">
    <div class="cert_header"><?=$name?></div>
</div>